### ISSUE TITLE
Switch button for dark/light theme

### ISSUE THREAD

**Issue by afcruzs** [steffen-wilke/darkfx#1]
Is it doable to extend this to have a 'opt-in' button that allows users to choose between dark/light themes?

It would be great if that value could be cached on the browser.

**Comment by perlun** [comment]
This would really be super cool! Just like what they already have at `docs.microsoft.com` (example page: https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/hello-world), where you can simply flip-switch between these modes. It persists in the browser in that case as well.

**Comment by cblackuk** [comment]
I would love to see the completion of this work too :-)
