### ISSUE TITLE
right menu dissapeared

### ISSUE THREAD

**Issue by gus-ghielec** [steffen-wilke/darkfx#7]
The right navigation that should show under the toggle switch disappeared. It is there in the demos but it is not showing on our website https://docs.ghielectronics.com/

**Comment by corrm** [comment]
Edit that file `partials/affix.tmpl.partial`
```
<nav class="bs-docs-sidebar hidden-print hidden-xs hidden-sm affix" id="affix">
    <h5>{{__global.inThisArticle}}</h5>
    <div></div>
    <p><a class="back-to-top" href="#top">Back to top</a><p>
</nav>
```
